# Fichier de déploiement pour Airflow sur Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels: {app: airflow}
  template:
    metadata:
      labels: {app: airflow}
    spec:
      serviceAccountName: airflow-ksa
      containers:
      - name: airflow-webserver
        image: europe-west1-docker.pkg.dev/fluid-stratum-475417-s9/airflow-apps/my-finance-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: ["bash", "-c", "/opt/airflow/dags/startup.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    app: airflow
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
